//
//  JSONValueTransformer+NSDate.h
//  FouleFactoryApi
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 09/14/2016
//

#import "JSONValueTransformer.h"

@interface JSONValueTransformer (NSDate)

-(NSDate*) NSDateFromNSString:(NSString*)string;

@end
