//
//  ProjectWriterServiceModel.h
//  FouleFactoryApi
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 09/16/2016
//
#ifndef APIMATIC_PROJECTWRITERSERVICEMODEL
#define APIMATIC_PROJECTWRITERSERVICEMODEL

#import <Foundation/Foundation.h>
#import "JSONModel.h"
#import "APIHelper.h"



//protocol defined for deserialization of JSON
@protocol ProjectWriterServiceModel
@end

@interface ProjectWriterServiceModel : JSONModel

/**
* TODO: Write general description for this field
*/
@property int idTemplate;

/**
* TODO: Write general description for this field
*/
@property NSString* title;

/**
* TODO: Write general description for this field
*/
@property NSString* estimatedTimePerTask;

/**
* TODO: Write general description for this field
*/
@property int nbSupplierPerTask;

/**
* TODO: Write general description for this field
*/
@property int amountWithoutTaxPerTask;

/**
* TODO: Write general description for this field
*/
@property BOOL automaticValidation;

/**
* TODO: Write general description for this field
*/
@property NSDate* maxEndDate;

/**
* TODO: Write general description for this field
*/
@property NSNumber* idCertification;

/**
* TODO: Write general description for this field
*/
@property NSString* urlNotification;


/**
* Key mappings for the json serialization and deserialization
*/
+(NSDictionary*) keyMap;

/**
* Key mapper for json serialization and deserialization
*/
+(JSONKeyMapper*) keyMapper;

/**
* Helps avoiding deserialization errors when one or more properties are missing
* @returns	True, indicating that all properties are optional for deserialization
*/
+(BOOL)propertyIsOptional:(NSString*) propertyName;

@end
#endif