//
//  ProjectWriterServiceModel.m
//  FouleFactoryApi
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 09/16/2016
//
#import "ProjectWriterServiceModel.h"

@implementation ProjectWriterServiceModel

/**
* TODO: Write general description for this method
*/
@synthesize idTemplate;

/**
* TODO: Write general description for this method
*/
@synthesize title;

/**
* TODO: Write general description for this method
*/
@synthesize estimatedTimePerTask;

/**
* TODO: Write general description for this method
*/
@synthesize nbSupplierPerTask;

/**
* TODO: Write general description for this method
*/
@synthesize amountWithoutTaxPerTask;

/**
* TODO: Write general description for this method
*/
@synthesize automaticValidation;

/**
* TODO: Write general description for this method
*/
@synthesize maxEndDate;

/**
* TODO: Write general description for this method
*/
@synthesize idCertification;

/**
* TODO: Write general description for this method
*/
@synthesize urlNotification;



/**
* Key mappings for the json serialization and deserialization
*/
+(NSDictionary*) keyMap
{
    NSMutableDictionary* map = [[NSMutableDictionary alloc] init];
    [map addEntriesFromDictionary: @{
        @"IdTemplate": @"idTemplate",
        @"Title": @"title",
        @"EstimatedTimePerTask": @"estimatedTimePerTask",
        @"NbSupplierPerTask": @"nbSupplierPerTask",
        @"AmountWithoutTaxPerTask": @"amountWithoutTaxPerTask",
        @"AutomaticValidation": @"automaticValidation",
        @"MaxEndDate": @"maxEndDate",
        @"IdCertification": @"idCertification",
        @"UrlNotification": @"urlNotification"  
    }];

    return map;
}

/**
* Key mapper for json serialization and deserialization
*/
+(JSONKeyMapper*) keyMapper
{ 
  return [[JSONKeyMapper alloc] initWithDictionary: [self keyMap]];
}

/**
* Helps avoiding deserialization errors when one or more properties are missing
* @returns	True, indicating that all properties are optional for deserialization
*/
+(BOOL)propertyIsOptional:(NSString*) propertyName
{
    return YES;
}

@end