//
//  TemplateNewWriterServiceModel.h
//  FouleFactoryApi
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 09/16/2016
//
#ifndef APIMATIC_TEMPLATENEWWRITERSERVICEMODEL
#define APIMATIC_TEMPLATENEWWRITERSERVICEMODEL

#import <Foundation/Foundation.h>
#import "JSONModel.h"
#import "APIHelper.h"

#import "TemplateInstructionWriterServiceModel.h"
#import "TemplateColumnWriterServiceModel.h"
#import "TemplateQuestionWriterServiceModel.h"


//protocol defined for deserialization of JSON
@protocol TemplateNewWriterServiceModel
@end

@interface TemplateNewWriterServiceModel : JSONModel

/**
* TODO: Write general description for this field
*/
@property int idProjectType;

/**
* TODO: Write general description for this field
*/
@property NSString* title;

/**
* TODO: Write general description for this field
*/
@property NSString* description;

/**
* TODO: Write general description for this field
*/
@property NSArray<TemplateInstructionWriterServiceModel> * instructions;

/**
* TODO: Write general description for this field
*/
@property NSArray<TemplateColumnWriterServiceModel> * columns;

/**
* TODO: Write general description for this field
*/
@property NSArray<TemplateQuestionWriterServiceModel> * questions;


/**
* Key mappings for the json serialization and deserialization
*/
+(NSDictionary*) keyMap;

/**
* Key mapper for json serialization and deserialization
*/
+(JSONKeyMapper*) keyMapper;

/**
* Helps avoiding deserialization errors when one or more properties are missing
* @returns	True, indicating that all properties are optional for deserialization
*/
+(BOOL)propertyIsOptional:(NSString*) propertyName;

@end
#endif