//
//  TemplateNewWriterServiceModel.m
//  FouleFactoryApi
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 09/14/2016
//
#import "TemplateNewWriterServiceModel.h"

@implementation TemplateNewWriterServiceModel

/**
* TODO: Write general description for this method
*/
@synthesize idProjectType;

/**
* TODO: Write general description for this method
*/
@synthesize title;

/**
* TODO: Write general description for this method
*/
@synthesize description;

/**
* TODO: Write general description for this method
*/
@synthesize instructions;

/**
* TODO: Write general description for this method
*/
@synthesize columns;

/**
* TODO: Write general description for this method
*/
@synthesize questions;



/**
* Key mappings for the json serialization and deserialization
*/
+(NSDictionary*) keyMap
{
    NSMutableDictionary* map = [[NSMutableDictionary alloc] init];
    [map addEntriesFromDictionary: @{
        @"IdProjectType": @"idProjectType",
        @"Title": @"title",
        @"Description": @"description",
        @"Instructions": @"instructions",
        @"Columns": @"columns",
        @"Questions": @"questions"  
    }];

    return map;
}

/**
* Key mapper for json serialization and deserialization
*/
+(JSONKeyMapper*) keyMapper
{ 
  return [[JSONKeyMapper alloc] initWithDictionary: [self keyMap]];
}

/**
* Helps avoiding deserialization errors when one or more properties are missing
* @returns	True, indicating that all properties are optional for deserialization
*/
+(BOOL)propertyIsOptional:(NSString*) propertyName
{
    return YES;
}

@end