//
//  CsvFilesController.h
//  FouleFactoryApi
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 09/14/2016
//
#import <Foundation/Foundation.h>
#import "Configuration.h"
#import "APIHelper.h"
#import "APIError.h"
#import "BaseController.h"
#import "UnirestClient.h"
#import "HttpContext.h"
#import "NSDate+extension.h"
#import "CsvFileWriterServiceModel.h"

@interface CsvFilesController : BaseController

/**
* Completion block definition for asynchronous call to CsvFiles_CreateCsvFile */
typedef void (^CompletedPostCsvFilesCreateCsvFile)(BOOL success, HttpContext* context, id response, NSError* error);

/**
* Create new csv file
* @param    file    Required parameter: Example: 
* @param    acceptLanguage    Optional parameter: Example: fr
*/
- (void) createCsvFilesCreateCsvFileAsyncWithFile:(CsvFileWriterServiceModel*) file
                acceptLanguage:(NSString*) acceptLanguage
                completionBlock:(CompletedPostCsvFilesCreateCsvFile) onCompleted;

/**
* Completion block definition for asynchronous call to CsvFiles_Get */
typedef void (^CompletedGetCsvFilesGet)(BOOL success, HttpContext* context, id response, NSError* error);

/**
* Get csv file by id
* @param    mid    Required parameter: Example: 
* @param    acceptLanguage    Optional parameter: Example: fr
*/
- (void) getCsvFilesGetAsyncWithId:(int) mid
                acceptLanguage:(NSString*) acceptLanguage
                completionBlock:(CompletedGetCsvFilesGet) onCompleted;

@end