//
//  TaskAnswerTextsController.h
//  FouleFactoryApi
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 09/14/2016
//
#import <Foundation/Foundation.h>
#import "Configuration.h"
#import "APIHelper.h"
#import "APIError.h"
#import "BaseController.h"
#import "UnirestClient.h"
#import "HttpContext.h"
#import "NSDate+extension.h"

@interface TaskAnswerTextsController : BaseController

/**
* Completion block definition for asynchronous call to TaskAnswerTexts_Get */
typedef void (^CompletedGetTaskAnswerTextsGet)(BOOL success, HttpContext* context, id response, NSError* error);

/**
* Get task answer text by id
* @param    mid    Required parameter: Example: 
* @param    acceptLanguage    Optional parameter: Example: fr
*/
- (void) getTaskAnswerTextsGetAsyncWithId:(int) mid
                acceptLanguage:(NSString*) acceptLanguage
                completionBlock:(CompletedGetTaskAnswerTextsGet) onCompleted;

@end