//
//  TasksController.h
//  FouleFactoryApi
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 09/14/2016
//
#import <Foundation/Foundation.h>
#import "Configuration.h"
#import "APIHelper.h"
#import "APIError.h"
#import "BaseController.h"
#import "UnirestClient.h"
#import "HttpContext.h"
#import "NSDate+extension.h"
#import "TaskValidationWriterServiceModel.h"

@interface TasksController : BaseController

/**
* Completion block definition for asynchronous call to Tasks_Validate */
typedef void (^CompletedPutTasksValidate)(BOOL success, HttpContext* context, id response, NSError* error);

/**
* Validate task
* @param    task    Required parameter: Example: 
* @param    acceptLanguage    Optional parameter: Example: fr
*/
- (void) updateTasksValidateAsyncWithTask:(TaskValidationWriterServiceModel*) task
                acceptLanguage:(NSString*) acceptLanguage
                completionBlock:(CompletedPutTasksValidate) onCompleted;

/**
* Completion block definition for asynchronous call to Tasks_GetAnswerChoices */
typedef void (^CompletedGetTasksGetAnswerChoices)(BOOL success, HttpContext* context, id response, NSError* error);

/**
* Get task answer choices by task id
* @param    mid    Required parameter: Example: 
* @param    acceptLanguage    Optional parameter: Example: fr
*/
- (void) getTasksGetAnswerChoicesAsyncWithId:(int) mid
                acceptLanguage:(NSString*) acceptLanguage
                completionBlock:(CompletedGetTasksGetAnswerChoices) onCompleted;

/**
* Completion block definition for asynchronous call to Tasks_GetAnswerTexts */
typedef void (^CompletedGetTasksGetAnswerTexts)(BOOL success, HttpContext* context, id response, NSError* error);

/**
* Get task answer texts by task id
* @param    mid    Required parameter: Example: 
* @param    acceptLanguage    Optional parameter: Example: fr
*/
- (void) getTasksGetAnswerTextsAsyncWithId:(int) mid
                acceptLanguage:(NSString*) acceptLanguage
                completionBlock:(CompletedGetTasksGetAnswerTexts) onCompleted;

/**
* Completion block definition for asynchronous call to Tasks_Get */
typedef void (^CompletedGetTasksGet)(BOOL success, HttpContext* context, id response, NSError* error);

/**
* Get task by id
* @param    mid    Required parameter: Example: 
* @param    acceptLanguage    Optional parameter: Example: fr
*/
- (void) getTasksGetAsyncWithId:(int) mid
                acceptLanguage:(NSString*) acceptLanguage
                completionBlock:(CompletedGetTasksGet) onCompleted;

@end