//
//  TemplatesController.h
//  FouleFactoryApi
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 09/16/2016
//
#import <Foundation/Foundation.h>
#import "Configuration.h"
#import "APIHelper.h"
#import "APIError.h"
#import "BaseController.h"
#import "UnirestClient.h"
#import "HttpContext.h"
#import "NSDate+extension.h"
#import "TemplateNewWriterServiceModel.h"

@interface TemplatesController : BaseController

/**
* Completion block definition for asynchronous call to Templates_CreateTemplate */
typedef void (^CompletedPostTemplatesCreateTemplate)(BOOL success, HttpContext* context, id response, NSError* error);

/**
* Create new template
* @param    template    Required parameter: Example: 
* @param    acceptLanguage    Optional parameter: Example: fr
*/
- (void) createTemplatesCreateTemplateAsyncWithTemplate:(TemplateNewWriterServiceModel*) template
                acceptLanguage:(NSString*) acceptLanguage
                completionBlock:(CompletedPostTemplatesCreateTemplate) onCompleted;

/**
* Completion block definition for asynchronous call to Templates_GetTemplates */
typedef void (^CompletedGetTemplatesGetTemplates)(BOOL success, HttpContext* context, id response, NSError* error);

/**
* Get all user templates id
*/
- (void) getTemplatesGetTemplatesWithCompletionBlock:(CompletedGetTemplatesGetTemplates) onCompleted;

/**
* Completion block definition for asynchronous call to Templates_GetTemplate */
typedef void (^CompletedGetTemplatesGetTemplate)(BOOL success, HttpContext* context, id response, NSError* error);

/**
* Get template by id
* @param    idTemplate    Required parameter: Example: 
* @param    acceptLanguage    Optional parameter: Example: fr
*/
- (void) getTemplatesGetTemplateAsyncWithIdTemplate:(int) idTemplate
                acceptLanguage:(NSString*) acceptLanguage
                completionBlock:(CompletedGetTemplatesGetTemplate) onCompleted;

@end